[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/socket.io/*"
to = "/.netlify/functions/socketio/:splat"
status = 200
force = true
